FROM nginx
USER root
COPY server/nginx/nginx.conf /etc/nginx/nginx.conf
COPY server/miniserver.c /home/miniserver.c
COPY entrypoint.sh /home/entrypoint.sh
RUN apt-get update && apt-get install -y gcc spawn-fcgi libfcgi-dev && chmod +x entrypoint.sh
WORKDIR /home/
CMD ["/home/entrypoint.sh"]